services:
  # Data-Diff N8N API 服务
  data-diff-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 114.114.114.114
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/datadiff
      - LOG_LEVEL=INFO
    volumes:
      - ./n8n:/app/n8n
    depends_on:
      - postgres
    networks:
      - datadiff-network
    restart: unless-stopped

  # N8N 工作流引擎
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PATH=/n8n/
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom-extensions
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=password
      - CLICKZETTA_API_URL=http://data-diff-api:8000/api/v1/connections/test
      - CLICKZETTA_SCHEMA_API_URL=http://data-diff-api:8000/api/v1/tables/list
      - DATABASE_API_URL=http://data-diff-api:8000/api/v1/connections/test
      - DATABASE_SCHEMA_API_URL=http://data-diff-api:8000/api/v1/tables/list
      # 新增的推荐配置
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/dist:/home/node/.n8n/custom-extensions:ro
    depends_on:
      - postgres
    networks:
      - datadiff-network
    restart: unless-stopped

  # PostgreSQL 数据库
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - datadiff-network
    restart: unless-stopped

  # Grafana 监控仪表板
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana-dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - datadiff-network
    restart: unless-stopped

  # Prometheus 指标收集
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090" # 将主机端口从 9090 更改为 9091，避免端口冲突
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # 精确挂载配置文件
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - datadiff-network
    restart: unless-stopped

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 修正配置文件路径
      - ./nginx/index.html:/usr/share/nginx/html/index.html # 挂载首页
      - ./nginx/certs:/etc/nginx/certs # 挂载证书目录
    depends_on:
      - data-diff-api
      - n8n
    networks:
      - datadiff-network
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:
  grafana_data:
  prometheus_data:

networks:
  datadiff-network:
    driver: bridge
