[tool.poetry]
name = "data-diff"
version = "0.0.2"
description = "A cross-database, efficient diff between mostly-similar database tables"
authors = ["Erez Shinnan <erezshin@gmail.com>"]
license = ""
readme = "README.md"
repository = "https://github.com/datafold/data-diff"
documentation = ""
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Topic :: Database :: Database Engines/Servers",
    "Typing :: Typed"
]
packages = [{ include = "data_diff" }]

[tool.poetry.dependencies]
python = "^3.7"
runtype = "^0.2.4"
dsnparse = "*"
pyparsing = "Ë†3.0"
click = "^8.1"

preql = { version = "^0.2.11", optional = true }
psycopg2 = { version = "*", optional = true }
mysql-connector-python = { version = "*", optional = true}
snowflake-connector-python = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
protobuf = "^3.20.1"

[tool.poetry.extras]
preql = ["preql"]
mysql = ["mysql-connector-python"]
pgsql = ["psycopg2"]
snowflake = ["snowflake-connector-python"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
data_diff = 'data_diff.__main__:main'