[tool.poetry]
name = "datafold-xdiff"
version = "0.0.1"
description = "A cross-database, efficient diff between mostly-similar database tables"
authors = ["Erez Shinnan <erezshin@gmail.com>"]
license = ""
readme = "README.md"
repository = "https://github.com/datafold/xdiff"
documentation = ""
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Topic :: Database :: Database Engines/Servers",
    "Typing :: Typed"
]
packages = [{ include = "xdiff" }]

[tool.poetry.dependencies]
python = "^3.6"
runtype = "^0.1.16"
dsnparse = "*"

psycopg2 = { version = "*", optional = true }
mysqlclient = { version = "*", optional = true }
snowflake-connector-python = { version = "*", optional = true }

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2"]
snowflake = ["snowflake-connector-python"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
preql = 'xdiff.__main__:main'