version: "3.8"

services:
    xdiff:
      container_name: xdiff
      build: 
        context: ../
        dockerfile: ./dev/Dockerfile
        args:
          - DB1_URI
          - TABLE1_NAME
          - DB2_URI
          - TABLE2_NAME
          - OPTIONS
      ports:
        - '9992:9992'
      expose:
        - '9992'
      tty: true
      networks:
        - local

    prepdb:
      container_name: prepdb
      build: 
        context: ../
        dockerfile: ./dev/Dockerfile
      command: ["bash", "./dev/prepdb.sh"]
      volumes: 
        - prepdb-data:/app:delegated
      ports:
        - '9991:9991'
      expose:
        - '9991'
      tty: true
      networks:
        - local

    postgres:
      container_name: postgresql
      image: postgres:14.1-alpine
      command: >
        -c work_mem=1GB
        -c maintenance_work_mem=1GB
        -c max_wal_size=8GB
      restart: always
      volumes: 
        - postgresql-data:/var/lib/postgresql/data:delegated
      ports:
        - '5432:5432'
      expose:
        - '5432'
      env_file:
        - dev.env
      tty: true
      networks:
        - local

    mysql:
      container_name: mysql
      image: "${MYSQL_IMAGE:-mysql}"
      command: >
        --default-authentication-plugin=mysql_native_password
        --innodb-buffer-pool-size=8G
        --innodb_io_capacity=2000
        --innodb_log_file_size=1G
        --binlog-cache-size=16M
        --key_buffer_size=0
        --max_connections=10
        --innodb_flush_log_at_trx_commit=2
        --innodb_flush_log_at_timeout=10
        --innodb_flush_method=O_DSYNC
        --innodb_log_compressed_pages=OFF
        --sync_binlog=0
      restart: always
      volumes: 
        - mysql-data:/var/lib/mysql:delegated
      user: mysql
      ports:
        - '3306:3306'
      expose:
        - '3306'
      env_file:
        - dev.env
      tty: true
      networks:
        - local

volumes:
  postgresql-data:
  mysql-data:
  prepdb-data:

networks:
  local:
    driver: bridge