version: "3.8"

services:
    xdiff:
      container_name: xdiff
      build: 
        context: ../
        dockerfile: ./dev/xdiff.Dockerfile
        args:
          - DB1_URI
          - TABLE1_NAME
          - DB2_URI
          - TABLE2_NAME
          - OPTIONS
      ports:
        - '9992:9992'
      expose:
        - '9992'
      tty: true
      depends_on:
        - 'postgres'
        - 'mysql'
      networks:
        - local

    prepdb:
      container_name: prepdb
      build: 
        context: ../
        dockerfile: ./dev/prepdb.Dockerfile
      volumes: 
        - prepdb-data:/app:delegated
      ports:
        - '9991:9991'
      expose:
        - '9991'
      tty: true
      depends_on:
        - 'postgres'
        - 'mysql'
      networks:
        - local

    postgres:
      container_name: postgresql
      image: postgres:14.1-alpine
      command: >
        -c work_mem=1GB                   # Reduce writing temporary disk files.
        -c maintenance_work_mem=1GB       # Improve VACUUM, CREATE INDEX, ALTER TABLE ADD FOREIGN KEY operations.
        -c max_wal_size=8GB               # Filling of the table with movie lens data creates an higher write  
                                          # load than the default assumption of 1GB/hour. 
      restart: always
      volumes: 
        - postgresql-data:/var/lib/postgresql/data:delegated
      ports:
        - '5432:5432'
      expose:
        - '5432'
      env_file:
        - .env
      tty: true
      networks:
        - local

    mysql:
      container_name: mysql
      image: "${MYSQL_IMAGE:-mysql}"
      command: >
        --default-authentication-plugin=mysql_native_password  # Required for setting password via env vars.
        --innodb-buffer-pool-size=8G                           # Recommendation is to set to 50-75% of available 
                                                               # memmory. However, this is no dedicated instance. 
        --innodb_io_capacity=2000                              # Default setting is for hard drives. SSD benefits 
                                                               # from higher values.
        --innodb_log_file_size=1G                              # Tuning recommendation based on the 
                                                               # innodb-buffer-pool-size setting.
        --binlog-cache-size=16M                                # Tuning recommendation
        --key_buffer_size=0                                    # No MyISAM tables, InnoDB engine is used.
        --max_connections=10                                   # Test setup, not a lot connection needed.
        --innodb_flush_log_at_trx_commit=2                     # Reduce creation of logs for performance.
        --innodb_flush_log_at_timeout=10                       # Idem
        --innodb_flush_method=O_DSYNC                          # Suffers less from race conditions than fsync.
        --innodb_log_compressed_pages=OFF                      # To write less data to the redo_log.
        --sync_binlog=0                                        # Disables synchronization of the binary log to disk 
                                                               # by the MySQL server. Instead, the MySQL server relies 
                                                               # on the operating system to flush the binary log to 
                                                               # disk from time to time as it does for any other file. 
                                                               # This setting provides the best performance.
      restart: always
      volumes: 
        - mysql-data:/var/lib/mysql:delegated
      user: mysql
      ports:
        - '3306:3306'
      expose:
        - '3306'
      env_file:
        - .env
      tty: true
      networks:
        - local

volumes:
  postgresql-data:
  mysql-data:
  prepdb-data:

networks:
  local:
    driver: bridge