name: formatter
on:
    pull_request:
        branches: [ master ]
    
    workflow_dispatch:

jobs:
  linter_name:
    name: runner / ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the ruff formatter
        uses: chartboost/ruff-action@v1
        id: ruff_formatter
        with:
          args: format
      - name: Auto commit ruff formatting
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style fixes by ruff'